#!/bin/bash

echo "========================================="
echo "DEPRECATED: build-base-image.sh"
echo "========================================="
echo ""
echo "This script is deprecated in Dynamo v0.4.0."
echo ""
echo "NVIDIA Dynamo v0.4.0 uses prebuilt NGC containers:"
echo "  - nvcr.io/nvidia/ai-dynamo/vllm-runtime:v0.4.0"
echo "  - nvcr.io/nvidia/ai-dynamo/sglang-runtime:v0.4.0"
echo "  - nvcr.io/nvidia/ai-dynamo/trtllm-runtime:v0.4.0"
echo "  - nvcr.io/nvidia/ai-dynamo/dynamo:v0.4.0"
echo ""
echo "No custom base image building is required."
echo ""
echo "To deploy Dynamo examples:"
echo "  ./deploy.sh [example-name]"
echo ""
echo "Available examples:"
echo "  - hello-world"
echo "  - vllm" 
echo "  - sglang"
echo "  - trtllm"
echo "  - multinode-vllm"
echo ""
exit 1